version: '3'
services:
  web:
    image: nginx
    container_name: nginxbackdrop
    ports:
      - "8080:80"
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - .:/var/www
    restart: always
    working_dir: "/var/www"
    depends_on:
      - php
  php:
    build:
      context: docker/php
      args:
        TIMEZONE: Europe/London
    container_name: backdrop
    volumes:
      - .:/var/www
    restart: always
    working_dir: "/var/www"
    environment:
      BACKDROP_DB_HOST: "${BACKDROP_DB_HOST}"
      BACKDROP_DB_PORT: "${BACKDROP_DB_PORT}"
      BACKDROP_DB_NAME: "${BACKDROP_DB_NAME}"
      BACKDROP_DB_USER: "${BACKDROP_DB_USER}"
      BACKDROP_DB_PASSWORD: "${BACKDROP_DB_USER_PASSWORD}"
      BACKDROP_ADMIN_PASSWORD: "${BACKDROP_ADMIN_PASSWORD}"
    depends_on:
      - db
      - composer
  composer:
    image: composer
    volumes:
      - .:/var/www
    working_dir: "/var/www"
  db:
    image: mariadb:latest
    container_name: ${BACKDROP_DB_HOST}
    ports:
      - ${BACKDROP_DB_PORT}:3306
    volumes:
      - ./mysql:/var/lib/mysql
      - ./docker/mysql/custom-mysql.conf:/etc/mysql/conf.d/custom.cnf
    environment:
      MYSQL_DATABASE: "${BACKDROP_DB_NAME}"
      MYSQL_ROOT_PASSWORD: "${BACKDROP_DB_ROOT_PASSWORD}"
      MYSQL_USER: "${BACKDROP_DB_USER}"
      MYSQL_PASSWORD: "${BACKDROP_DB_USER_PASSWORD}"
      
networks:
  default:
    external:
      name: web
