version: '3'
services:
  web:
    image: nginx
    container_name: nginxbackdrop
    ports:
      - "8080:80"
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - .:/var/www
    restart: always
    working_dir: "/var/www"
    depends_on:
      - php
  php:
    build:
      context: docker/php
      args:
        TIMEZONE: Europe/London
    container_name: backdrop
    volumes:
      - .:/var/www
    restart: always
    working_dir: "/var/www"
    user: www-data
    environment:
      BACKDROP_DB_HOST: "${BACKDROP_DB_HOST}"
      BACKDROP_DB_PORT: "${BACKDROP_DB_PORT}"
      BACKDROP_DB_NAME: "${BACKDROP_DB_NAME}"
      BACKDROP_DB_USER: "${BACKDROP_DB_USER}"
      BACKDROP_DB_PASSWORD: "${BACKDROP_DB_USER_PASSWORD}"
      BACKDROP_ADMIN_EMAIL: "${BACKDROP_ADMIN_EMAIL}"
      BACKDROP_ADMIN_PASSWORD: "${BACKDROP_ADMIN_PASSWORD}"
      CIVICRM_GENDATA: "${CIVICRM_GENDATA}"
      CIVICRM_HOSTNAME: "${CIVICRM_HOSTNAME}"
    extra_hosts:
      - "civicrm.local:${HOST_MACHINE_IP}"
    depends_on:
      - dbbackdrop
      - dbcivicrm
      - composer
  composer:
    image: composer
    volumes:
      - .:/var/www
    working_dir: "/var/www"
  maildev:
    image: djfarrelly/maildev:latest
    container_name: civicrmmail
    ports:
      - "1080:80"
      - "2525:25"
    restart: always
  dbbackdrop:
    image: mariadb:latest
    container_name: ${BACKDROP_DB_HOST}
    ports:
      - ${BACKDROP_DB_PORT}:3306
    volumes:
      - ./mysql/backdrop:/var/lib/mysql
      - ./docker/mysql/custom-mysql.conf:/etc/mysql/conf.d/custom.cnf
    restart: always
    environment:
      MYSQL_DATABASE: "${BACKDROP_DB_NAME}"
      MYSQL_ROOT_PASSWORD: "${BACKDROP_DB_ROOT_PASSWORD}"
      MYSQL_USER: "${BACKDROP_DB_USER}"
      MYSQL_PASSWORD: "${BACKDROP_DB_USER_PASSWORD}"
  dbcivicrm:
    image: mariadb:latest
    container_name: ${CIVICRM_DB_HOST}
    ports:
      - ${CIVICRM_DB_PORT}:3306
    volumes:
      - ./mysql/civicrm:/var/lib/mysql
      - ./docker/mysql/custom-mysql.conf:/etc/mysql/conf.d/custom.cnf
    restart: always
    environment:
      MYSQL_DATABASE: "${CIVICRM_DB_NAME}"
      MYSQL_ROOT_PASSWORD: "${BACKDROP_DB_ROOT_PASSWORD}"
      MYSQL_USER: "${BACKDROP_DB_USER}"
      MYSQL_PASSWORD: "${BACKDROP_DB_USER_PASSWORD}"
      
networks:
  default:
    external:
      name: web
